# Generated by Django 3.0.6 on 2020-07-09 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addressbook_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_manage_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('Order_Type', models.CharField(blank=True, max_length=120, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Quentity', models.IntegerField(default=0)),
                ('Amount', models.IntegerField(default=0)),
                ('Order_Status', models.CharField(blank=True, default='Pending', help_text='Status may be Pending, Celler, Refunded, Canclled, Failled', max_length=120, null=True)),
                ('Payment_Status', models.BooleanField(default=False)),
                ('Payment_Method', models.CharField(blank=True, max_length=120, null=True)),
                ('Order_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_Date', models.DateTimeField(blank=True, null=True)),
                ('Payment_Date', models.DateTimeField(blank=True, null=True)),
                ('Order_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_AwAddressBook', to='addressbook_user.AwAddressBook')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aw Orders',
            },
        ),
        migrations.CreateModel(
            name='AwOrederItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=120)),
                ('Type', models.CharField(max_length=120)),
                ('Case_Formate', models.CharField(max_length=120)),
                ('Cost_of_product', models.FloatField(default=0)),
                ('Quentity', models.IntegerField(default=0)),
                ('Total_cost', models.FloatField(default=0)),
                ('Order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderId_OrderItem', to='orders.AwOrders')),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_OrderItem', to='admin_manage_products.AwProducts')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_OrderItem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aw Order Items',
            },
        ),
        migrations.CreateModel(
            name='AwAddToCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=120)),
                ('Type', models.CharField(max_length=120)),
                ('Quentity', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Case_Formate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Case_Formate_AwProductPrice', to='admin_manage_products.AwProductPrice')),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwProducts_AwAddToCard', to='admin_manage_products.AwProducts')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_AwAddToCard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aw Add To Card',
            },
        ),
    ]
