# Generated by Django 3.0.6 on 2020-07-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwOrderNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.TextField(blank=True, null=True)),
                ('Attachment', models.ImageField(blank=True, null=True, upload_to=orders.models.user_directory_path)),
                ('Display_Status', models.BooleanField(default=False)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderId_AwOrderNote', to='orders.AwOrders')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_AwOrderNote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aw Order Note',
            },
        ),
    ]
