# Generated by Django 3.0.6 on 2020-07-16 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_awordernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awordernote',
            name='Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
