# Generated by Django 3.0.6 on 2020-08-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200724_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='aworders',
            name='Use_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
