# Generated by Django 3.0.6 on 2020-08-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_aworders_use_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aworders',
            old_name='Cupon',
            new_name='Cupon_Code',
        ),
    ]
