# Generated by Django 3.0.6 on 2020-08-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200801_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aworders',
            name='Cupon_Discount',
            field=models.FloatField(default=0),
        ),
    ]
