# Generated by Django 3.0.6 on 2020-08-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200801_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aworders',
            name='Order_Status',
            field=models.BooleanField(default=False),
        ),
    ]
