# Generated by Django 3.0.6 on 2020-08-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0005_auto_20200718_0526'),
        ('orders', '0008_auto_20200804_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='aworederitem',
            name='Case_Formate_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='aworederitem',
            name='Case_Formate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Case_Formate_AwOrderitem', to='admin_manage_products.AwProductPrice'),
        ),
    ]
