# Generated by Django 3.0.6 on 2020-08-22 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_event', '0008_auto_20200818_1300'),
        ('orders', '0009_auto_20200805_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awaddtocard',
            old_name='Product',
            new_name='Product_Cellar',
        ),
        migrations.AddField(
            model_name='awaddtocard',
            name='Event_Ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwEvent_AwAddToCard', to='manage_event.AwEvent'),
        ),
        migrations.AddField(
            model_name='awaddtocard',
            name='Order_Type',
            field=models.CharField(default='Cellar', max_length=120),
        ),
        migrations.AddField(
            model_name='awaddtocard',
            name='Product_Delivered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwProducts_AwAddToCard_Delivered', to='orders.AwOrederItem'),
        ),
        migrations.AlterField(
            model_name='awaddtocard',
            name='Type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='awaddtocard',
            name='Year',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
