# Generated by Django 3.0.6 on 2020-08-22 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_event', '0008_auto_20200818_1300'),
        ('admin_manage_products', '0005_auto_20200718_0526'),
        ('orders', '0010_auto_20200822_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aworederitem',
            name='Product',
        ),
        migrations.AddField(
            model_name='awordernote',
            name='Order_For',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aworederitem',
            name='Event_Ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwEvent_AwOrederItem', to='manage_event.AwEvent'),
        ),
        migrations.AddField(
            model_name='aworederitem',
            name='Product_Cellar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwProducts_AwOrederItem', to='admin_manage_products.AwProducts'),
        ),
        migrations.AddField(
            model_name='aworederitem',
            name='Product_Delivered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwProducts_AwOrederItem_Delivered', to='admin_manage_products.AwProducts'),
        ),
        migrations.AlterField(
            model_name='aworederitem',
            name='Type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='aworederitem',
            name='Year',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
