# Generated by Django 3.0.6 on 2020-08-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0005_auto_20200718_0526'),
        ('orders', '0011_auto_20200822_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaddtocard',
            name='Product_Delivered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwProducts_AwAddToCard_Delivered', to='admin_manage_products.AwProducts'),
        ),
    ]
