# Generated by Django 3.0.6 on 2020-08-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200822_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='awaddtocard',
            name='Cost',
            field=models.FloatField(default=0),
        ),
    ]
