# Generated by Django 3.0.6 on 2020-08-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200822_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='awaddtocard',
            name='order_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwProducts_AwAddToCard_Delivered', to='orders.AwOrederItem'),
        ),
    ]
