# Generated by Django 3.0.6 on 2020-08-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_awaddtocard_order_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aworders',
            name='Order_Status_Set',
            field=models.CharField(default='Active', max_length=120),
        ),
    ]
