# Generated by Django 3.0.6 on 2020-09-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_aworders_order_status_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='awaddtocard',
            name='Cookies_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
