# Generated by Django 3.0.6 on 2020-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_awaddtocard_cookies_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaddtocard',
            name='Cookies_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
