# Generated by Django 3.0.6 on 2020-10-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200929_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='aworders',
            name='order_place',
            field=models.BooleanField(default=False),
        ),
    ]
