# Generated by Django 3.0.6 on 2020-10-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20201016_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='aworederitem',
            name='Duty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aworederitem',
            name='Gst',
            field=models.FloatField(default=0),
        ),
    ]
