# Generated by Django 3.0.6 on 2020-10-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20201016_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='aworders',
            name='shipping_Payment_Method',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aworders',
            name='shipping_Payment_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aworders',
            name='shipping_charge',
            field=models.IntegerField(default=0),
        ),
    ]
