# Generated by Django 3.0.6 on 2020-07-09 08:29

import admin_manage_categoryes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=120, unique=True)),
                ('Title', models.CharField(max_length=500)),
                ('Image', models.ImageField(upload_to=admin_manage_categoryes.models.user_directory_path)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Status', models.BooleanField(default=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Created_by_AwCategoryes', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Updated_by_AwCategoryes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AW Categoryes',
            },
        ),
    ]
