# Generated by Django 3.0.6 on 2020-08-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awpaymentmethod',
            name='active_status',
        ),
    ]
