# Generated by Django 3.0.6 on 2020-08-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0002_remove_awpaymentmethod_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='awpaymentmethod',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
