# Generated by Django 3.0.6 on 2020-08-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0003_awpaymentmethod_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='awpaymentmethod',
            name='Pay_on_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awpaymentmethod',
            name='Paypal',
            field=models.BooleanField(default=False),
        ),
    ]
