# Generated by Django 3.0.6 on 2020-08-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0005_auto_20200820_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awpaymentmethod',
            name='Expiry_Date',
            field=models.DateField(),
        ),
    ]
