# Generated by Django 3.0.6 on 2020-08-20 10:09

from django.db import migrations
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0006_auto_20200820_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awpaymentmethod',
            name='Expiry_Date',
            field=django_date_extensions.fields.ApproximateDateField(),
        ),
    ]
