# Generated by Django 3.0.6 on 2020-07-10 12:43

import admin_manage_country.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awcountry',
            name='Country_Banner_Image',
            field=models.ImageField(blank=True, null=True, upload_to=admin_manage_country.models.user_directory_path_banner),
        ),
    ]
