# Generated by Django 3.0.6 on 2020-07-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_country', '0002_awcountry_country_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='awcountry',
            name='Slug',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
