# Generated by Django 3.0.6 on 2020-09-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_country', '0003_awcountry_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awcountry',
            old_name='Country_Banner_Image',
            new_name='Banner_Image',
        ),
    ]
