# Generated by Django 3.0.6 on 2020-07-09 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_manage_country', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwAddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=120)),
                ('Last_Name', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=120)),
                ('Pnone_no', models.IntegerField(default=0)),
                ('Conpany_Name', models.CharField(blank=True, max_length=120, null=True)),
                ('Address', models.TextField()),
                ('Address_2', models.TextField(blank=True, null=True)),
                ('City', models.CharField(max_length=120)),
                ('State', models.CharField(blank=True, max_length=120, null=True)),
                ('Postcode', models.IntegerField(default=0)),
                ('Landark', models.CharField(blank=True, max_length=120, null=True)),
                ('Create_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_Address', to='admin_manage_country.AwCountryUser')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AW Address Book',
            },
        ),
    ]
