# Generated by Django 3.0.6 on 2020-07-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaddressbook',
            name='State',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
