# Generated by Django 3.0.6 on 2020-09-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook_user', '0002_auto_20200709_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awaddressbook',
            old_name='Landark',
            new_name='Landmark',
        ),
    ]
