# Generated by Django 3.0.6 on 2020-09-02 10:14

import admin_manage_setting.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwAllCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Aw All Country',
            },
        ),
        migrations.CreateModel(
            name='AwManageShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Free_Shipping_Amount', models.FloatField(default=0)),
                ('Free_Flat_Shipping', models.FloatField(default=0)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwManageShipping_Country', to='admin_manage_setting.AwAllCountry')),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwManageShipping_Created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aw Manage Shipping',
            },
        ),
        migrations.CreateModel(
            name='AwAdminSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=120, unique=True)),
                ('Product_Tag_Line', models.CharField(max_length=120, unique=True)),
                ('Logo', models.ImageField(upload_to=admin_manage_setting.models.user_directory_path)),
                ('favicon', models.ImageField(upload_to=admin_manage_setting.models.user_favicon_directory_path)),
                ('Duty', models.FloatField(default=0)),
                ('GST', models.FloatField(default=0)),
                ('Analytics', models.TextField(blank=True, null=True)),
                ('Facebook', models.URLField(blank=True, null=True)),
                ('Twitter', models.URLField(blank=True, null=True)),
                ('Linkedin', models.URLField(blank=True, null=True)),
                ('Instgram', models.URLField(blank=True, null=True)),
                ('Google', models.URLField(blank=True, null=True)),
                ('Yelp', models.URLField(blank=True, null=True)),
                ('EMAIL_HOST', models.CharField(max_length=120, unique=True)),
                ('EMAIL_USE_TLS', models.BooleanField(default=True)),
                ('EMAIL_PORT', models.IntegerField(default=0)),
                ('EMAIL_HOST_USER', models.EmailField(max_length=254)),
                ('EMAIL_HOST_PASSWORD', models.CharField(max_length=120, unique=True)),
                ('Manage_Delivery_Countries', models.ManyToManyField(related_name='AwAdminSetting_Vintage', to='admin_manage_setting.AwAllCountry')),
            ],
            options={
                'verbose_name_plural': 'Aw Admin Setting',
            },
        ),
    ]
