# Generated by Django 3.0.6 on 2020-09-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_setting', '0002_auto_20200902_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awadminsetting',
            old_name='Product_Name',
            new_name='Project_Name',
        ),
        migrations.RenameField(
            model_name='awadminsetting',
            old_name='Product_Tag_Line',
            new_name='Project_Tag_Line',
        ),
    ]
