# Generated by Django 3.0.6 on 2020-09-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_country', '0003_awcountry_slug'),
        ('admin_manage_setting', '0003_auto_20200902_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awmanageshipping',
            name='Country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwManageShipping_Country', to='admin_manage_country.AwCountryUser'),
        ),
    ]
