# Generated by Django 3.0.6 on 2020-10-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_setting', '0004_auto_20200906_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awmanageshipping',
            old_name='Free_Flat_Shipping',
            new_name='Shiping_Fees_min_order_amount',
        ),
        migrations.RenameField(
            model_name='awmanageshipping',
            old_name='Free_Shipping_Amount',
            new_name='min_ordr_amount_amount',
        ),
    ]
