# Generated by Django 3.0.6 on 2020-10-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_country', '0004_auto_20200921_1429'),
        ('admin_manage_setting', '0006_auto_20201015_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awmanageshipping',
            name='Country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwManageShipping_Country', to='admin_manage_country.AwCountryUser', unique=True),
        ),
    ]
