# Generated by Django 3.0.6 on 2020-06-22 09:18

from django.db import migrations, models
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwCmsPaage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120, unique=True)),
                ('Keyword', models.CharField(max_length=120, unique=True)),
                ('Background_Image', models.ImageField(upload_to=home.models.user_directory_path)),
                ('description', models.TextField()),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Aw Cms Paage',
            },
        ),
    ]
