# Generated by Django 3.0.6 on 2020-06-22 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20200622_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='awcmspaage',
            name='Created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_AwCmsPaage_Created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='awcmspaage',
            name='Updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_AwCmsPaage_Updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
