# Generated by Django 3.0.6 on 2020-09-25 12:41

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200622_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwPateTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page_Name', models.CharField(max_length=120, unique=True)),
                ('keyword', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Aw Page Name',
            },
        ),
        migrations.CreateModel(
            name='AwPageContent',
            fields=[
                ('Page_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.AwPateTitle')),
                ('Page_Title', models.CharField(max_length=120)),
                ('Banner_image', models.ImageField(upload_to=home.models.AwPageContent_directory_path)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aw Page Content',
            },
        ),
    ]
