# Generated by Django 3.0.6 on 2020-09-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_awpagecontent_awpatetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awcmspaage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
