# Generated by Django 3.0.6 on 2020-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200925_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='awcmspaage',
            name='Short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
