# Generated by Django 3.0.6 on 2020-10-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_awcmspaage_short_description_show_in_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awcmspaage',
            name='Short_description_Show_in_Footer',
            field=models.BooleanField(default=False),
        ),
    ]
