# Generated by Django 3.0.6 on 2020-10-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201006_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='awcmspaage',
            name='Publish',
            field=models.BooleanField(default=True),
        ),
    ]
