# Generated by Django 3.0.6 on 2020-07-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_grape', '0003_auto_20200710_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awgrape',
            name='Grape_Slug',
        ),
    ]
