# Generated by Django 3.0.6 on 2020-07-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_grape', '0004_remove_awgrape_grape_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='awgrape',
            name='Slug',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
