# Generated by Django 3.0.6 on 2020-07-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_grape', '0007_awgrape_shoort_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awgrape',
            old_name='Shoort_Description',
            new_name='Short_Description',
        ),
    ]
