# Generated by Django 3.0.6 on 2020-09-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_grape', '0008_auto_20200718_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awgrape',
            old_name='Grape_banner_Image',
            new_name='banner_Image',
        ),
    ]
