# Generated by Django 3.0.6 on 2020-09-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awnotification',
            name='Send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
