# Generated by Django 3.0.6 on 2020-09-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_notification', '0002_awnotification_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awnotification',
            name='Send_Status',
            field=models.BooleanField(default=False),
        ),
    ]
