# Generated by Django 3.0.6 on 2020-07-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awuserinfo',
            options={'verbose_name_plural': 'Aw User Info'},
        ),
    ]
