# Generated by Django 3.0.6 on 2020-07-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_auto_20200710_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awuserinfo',
            options={'verbose_name_plural': 'Aw User Infg'},
        ),
    ]
