# Generated by Django 3.0.6 on 2020-07-09 08:29

import admin_manage_products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_manage_color', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_manage_varietals', '0001_initial'),
        ('admin_manage_categoryes', '0001_initial'),
        ('admin_manage_size', '0001_initial'),
        ('admin_manage_region', '0001_initial'),
        ('admin_manage_classification', '0001_initial'),
        ('admin_manage_appellation', '0001_initial'),
        ('admin_manage_Vintages', '0001_initial'),
        ('admin_manage_grape', '0001_initial'),
        ('admin_manage_country', '0001_initial'),
        ('admin_manage_producer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwWineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=120, unique=True)),
                ('Status', models.BooleanField(default=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwWineType_Created_by', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwWineType_Updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aw Wine Type',
            },
        ),
        migrations.CreateModel(
            name='AwProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.CharField(max_length=120, unique=True)),
                ('Product_name', models.CharField(max_length=120, unique=True)),
                ('Product_slug', models.CharField(max_length=120, unique=True)),
                ('Status', models.BooleanField(default=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Meta_Title', models.CharField(blank=True, max_length=120, null=True)),
                ('Meta_Keyword', models.CharField(blank=True, max_length=120, null=True)),
                ('Meta_Description', models.TextField(blank=True, null=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Appellation', models.ManyToManyField(related_name='AwProducts_Appellation', to='admin_manage_appellation.AwAppellation')),
                ('Bottel_Size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProducts_Bottel_Size', to='admin_manage_size.AwSize')),
                ('Category', models.ManyToManyField(related_name='AwProducts_Category', to='admin_manage_categoryes.AwCategory')),
                ('Classification', models.ManyToManyField(related_name='AwProducts_Classification', to='admin_manage_classification.AwClassification')),
                ('Color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProducts_Color', to='admin_manage_color.AwColor')),
                ('Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProducts_Country', to='admin_manage_country.AwCountry')),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProducts_Created_by', to=settings.AUTH_USER_MODEL)),
                ('Grape', models.ManyToManyField(related_name='AwProducts_Grape', to='admin_manage_grape.AwGrape')),
                ('Producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProducts_Producer', to='admin_manage_producer.AwProducers')),
                ('Regions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProducts_Regions', to='admin_manage_region.AwRegion')),
                ('Select_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProducts_Created_by', to='admin_manage_products.AwWineType')),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProducts_Updated_by', to=settings.AUTH_USER_MODEL)),
                ('Varietals', models.ManyToManyField(related_name='AwProducts_Varietals', to='admin_manage_varietals.AwVarietals')),
                ('Vintage', models.ManyToManyField(related_name='AwProducts_Vintage', to='admin_manage_Vintages.AwVintages')),
            ],
            options={
                'verbose_name_plural': 'Aw Products',
            },
        ),
        migrations.CreateModel(
            name='AwProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bottle', models.CharField(blank=True, max_length=120, null=True)),
                ('Retail_Cost', models.FloatField(default=0)),
                ('Retail_Stock', models.IntegerField(default=0)),
                ('Descount_Cost', models.FloatField(default=0)),
                ('Duty', models.FloatField(default=0)),
                ('GST', models.FloatField(default=0)),
                ('Bond_Cost', models.FloatField(default=0)),
                ('Bond_Stock', models.IntegerField(default=0)),
                ('Bond_Descount_Cost', models.FloatField(default=0)),
                ('Other_info', models.TextField(blank=True, null=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProductPrice_Created_by', to=settings.AUTH_USER_MODEL)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwProductPrice_Product', to='admin_manage_products.AwProducts')),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProductPrice_Updated_by', to=settings.AUTH_USER_MODEL)),
                ('Vintage_Year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProductPrice_Vintage_Year', to='admin_manage_Vintages.AwVintages')),
            ],
            options={
                'verbose_name_plural': 'Aw Product Price & Stock',
            },
        ),
        migrations.CreateModel(
            name='AwProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_Type', models.CharField(blank=True, max_length=120, null=True)),
                ('Image', models.ImageField(upload_to=admin_manage_products.models.user_directory_path)),
                ('Status', models.BooleanField(default=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProductImage_Created_by', to=settings.AUTH_USER_MODEL)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwProductImage_Product', to='admin_manage_products.AwProducts')),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProductImage_Updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aw Product Image',
            },
        ),
    ]
