# Generated by Django 3.0.6 on 2020-07-17 12:31

import admin_manage_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0002_awproducts_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awproducts',
            name='Product_image',
            field=models.ImageField(blank=True, null=True, upload_to=admin_manage_products.models.user_directory_path_for_product),
        ),
    ]
