# Generated by Django 3.0.6 on 2020-07-18 05:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0003_auto_20200717_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awproducts',
            name='Product_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='Product_name', unique_with=('pub_date__month',)),
        ),
    ]
