# Generated by Django 3.0.6 on 2020-09-11 09:32

import admin_manage_products.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0005_auto_20200718_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwProductImageFullView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to=admin_manage_products.models.user_directory_path)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwProductImageFullView_Product', to='admin_manage_products.AwProducts')),
            ],
            options={
                'verbose_name_plural': 'Aw Product Image 360',
            },
        ),
    ]
