# Generated by Django 3.0.6 on 2020-09-11 12:53

import admin_manage_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0006_awproductimagefullview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awproductimagefullview',
            name='Image',
            field=models.ImageField(upload_to=admin_manage_products.models.user_directory_path_for_image_full),
        ),
    ]
