# Generated by Django 3.0.6 on 2021-01-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_size', '0001_initial'),
        ('admin_manage_products', '0007_auto_20200911_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awproducts',
            name='Bottel_Size',
        ),
        migrations.AddField(
            model_name='awproducts',
            name='Bottel_Size',
            field=models.ManyToManyField(related_name='AwProducts_Bottel_Size', to='admin_manage_size.AwSize'),
        ),
    ]
