# Generated by Django 3.0.6 on 2020-07-10 11:16

import admin_manage_producer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_producer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awproducers',
            name='Producer_Banner_Image',
            field=models.ImageField(blank=True, null=True, upload_to=admin_manage_producer.models.user_directory_path_banner),
        ),
    ]
