# Generated by Django 3.0.6 on 2020-09-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_producer', '0003_awproducers_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awproducers',
            old_name='Producer_Banner_Image',
            new_name='Banner_Image',
        ),
    ]
