# Generated by Django 3.0.6 on 2020-09-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0007_auto_20200911_1253'),
        ('user_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awwishlist',
            name='Case_Formate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Case_Formate_AwWishList', to='admin_manage_products.AwProductPrice'),
        ),
    ]
