# Generated by Django 3.0.6 on 2020-09-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_wishlist', '0002_awwishlist_case_formate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awwishlist',
            name='Year',
        ),
    ]
