# Generated by Django 3.0.6 on 2020-07-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_region', '0002_awregion_region_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='awregion',
            name='Short_Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
