# Generated by Django 3.0.6 on 2020-08-19 07:05

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manage_wine_recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_manage_products', '0005_auto_20200718_0526'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwWineRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120, unique=True)),
                ('Slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='Name', unique_with=('Created_date__month',))),
                ('Image', models.ImageField(upload_to=manage_wine_recipes.models.user_directory_path)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwWineRecipes_Created_by', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwWineRecipes_Updated_by', to=settings.AUTH_USER_MODEL)),
                ('Wine_With_Recipes', models.ManyToManyField(related_name='AwWineRecipes_Wine_With_Recipes', to='admin_manage_products.AwProducts')),
            ],
            options={
                'verbose_name_plural': 'Aw Wine Recipes',
            },
        ),
    ]
