# Generated by Django 3.0.6 on 2020-08-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_wine_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awwinerecipes',
            name='Shoort_Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
