# Generated by Django 3.0.6 on 2020-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_wine_recipes', '0002_awwinerecipes_shoort_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='awwinerecipes',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
