# Generated by Django 3.0.6 on 2020-08-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_wine_recipes', '0003_awwinerecipes_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awwinerecipes',
            old_name='Shoort_Description',
            new_name='Short_Description',
        ),
    ]
