# Generated by Django 3.0.8 on 2020-07-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_perferences', '0003_auto_20200715_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_interests',
            old_name='Type',
            new_name='Select_Type',
        ),
        migrations.RenameField(
            model_name='service_interests',
            old_name='Name',
            new_name='Service_interests_name',
        ),
    ]
