# Generated by Django 3.0.6 on 2020-07-22 08:46

import admin_manage_dinner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_dinner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awdinner',
            name='Dinner_Image',
            field=models.ImageField(blank=True, null=True, upload_to=admin_manage_dinner.models.user_directory_path),
        ),
    ]
