# Generated by Django 3.0.6 on 2020-08-17 07:11

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manage_event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(max_length=120, unique=True)),
                ('Slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='Event_name', unique_with=('Created_date__month',))),
                ('Description', models.TextField(blank=True, null=True)),
                ('Event_Image', models.ImageField(upload_to=manage_event.models.user_directory_path)),
                ('Start_Date', models.DateTimeField(default=0)),
                ('End_Date', models.DateTimeField(default=0)),
                ('ticket_pr_person', models.IntegerField(default=0)),
                ('ticket_price', models.FloatField(default=0)),
                ('Status', models.BooleanField(default=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Created_by_AwEvent', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Updated_by_AwEvent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AW Event',
            },
        ),
    ]
