# Generated by Django 3.0.6 on 2020-08-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awevent',
            name='Short_Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
