# Generated by Django 3.0.6 on 2020-08-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_event', '0002_awevent_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='awevent',
            name='Event_Host',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='awevent',
            name='Location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awevent',
            name='Producer_Notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
