# Generated by Django 3.0.6 on 2020-08-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_event', '0003_auto_20200818_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awevent',
            name='Event_Host',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
