# Generated by Django 3.0.6 on 2020-08-18 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_event', '0004_auto_20200818_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=120, unique=True)),
                ('Create_Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'AW Event Type',
            },
        ),
    ]
