# Generated by Django 3.0.6 on 2020-08-18 09:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_event', '0005_aweventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='aweventtype',
            name='Slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='Type', unique_with=('Created_date__month',)),
        ),
    ]
