# Generated by Django 3.0.6 on 2020-08-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_event', '0007_awevent_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aweventtype',
            old_name='Create_Date',
            new_name='Created_date',
        ),
    ]
