# Generated by Django 3.0.6 on 2020-07-24 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwCuponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CouponCode', models.CharField(max_length=120, unique=True)),
                ('Type', models.CharField(max_length=120)),
                ('Amount', models.FloatField(default=0)),
                ('Usage_Limit_Per_Coupon', models.IntegerField(default=0)),
                ('Usage_Limit_Per_User', models.IntegerField(default=0)),
                ('Valid_from', models.DateField()),
                ('Valid_to', models.DateField()),
                ('Status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'LS Cupon Code',
            },
        ),
    ]
